import contextvars
import typing as t

if t.TYPE_CHECKING:  # pragma: no cover
    from ninja_extra.context import RouteContext


POST = "POST"
PUT = "PUT"
PATCH = "PATCH"
DELETE = "DELETE"
GET = "GET"
HEAD = "HEAD"
OPTIONS = "OPTIONS"
TRACE = "TRACE"
ROUTE_METHODS = [POST, PUT, PATCH, DELETE, GET, HEAD, OPTIONS, TRACE]
THROTTLED_FUNCTION = "__throttled_endpoint__"
THROTTLED_OBJECTS = "__throttled_objects__"
ROUTE_FUNCTION = "__route_function__"

CONTROLLER_OPERATION_HANDLER_KEY = "CONTROLLER_OPERATION_HANDLER"
CONTROLLER_WATERMARK = "CONTROLLER_WATERMARK"
ROUTE_OBJECT = "ROUTE_OBJECT"
ROUTE_OBJECT_FUNCTION = "ROUTE_OBJECT_FUNCTION"
OPERATION_ENDPOINT_KEY = "OPERATION_ENDPOINT_KEY"
API_CONTROLLER_INSTANCE = "API_CONTROLLER_INSTANCE"
ORDERATOR_OBJECT = "ORDERATOR_WATERMARK"
SEARCH_OPERATOR_OBJECT = "SEARCH_OPERATOR_OBJECT"
PAGINATOR_OBJECT = "PAGINATOR_WATERMARK"
NINJA_EXTRA_API_CONTROLLER_REGISTERED_KEY = "NINJA_EXTRA_API_CONTROLLER_REGISTERED_KEY"

ROUTE_CONTEXT_VAR: contextvars.ContextVar[t.Optional["RouteContext"]] = (
    contextvars.ContextVar("ROUTE_CONTEXT_VAR")
)
ROUTE_CONTEXT_VAR.set(None)
