name: Test

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: make install
      - name: Test
        run: pytest --cov=ninja_extra --cov-report=xml tests
      - name: Coverage
        uses: codecov/codecov-action@v5
